name: caching

on: 
  workflow_dispatch:
    inputs:
      cache-use:
        type: boolean
        description: use cache or not 
        default: true 
        
jobs:
  #checkout the code 
  #install dependencies
  #unit , linting ,building 
  #deploy to prod 
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
       working-directory: caching-react/react-app 
    steps:
      - name: checkout the code 
        uses: actions/checkout@v4
      - name: setting up the node 
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: cache check 
        uses: actions/cache@v4
        if: inputs.cache-use
        id: cache 
        with:
          path: caching-react/react-app/node-modules
          key: deps-node-modules-${{ hashFiles('caching-react/react-app/package-lock.json')}}
      - name: building 
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci 
      - name: testing 
        run: npm run test 
      - name: deploying to prod 
        run: echo "deploying to prod ....."
