name: terraform pipeline 

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      dry-run:
        type: boolean 
        description: want to check the pipeline config
        default: false
      choose-environment:
        type: environment
        description: choose which environment to deploy 
        default: staging 
      tf-destroy:
        type: boolean
        description: do you need to destroy the pipeline? 
        default: false 
permissions:
  id-token: write
  contents: read
  pull-requests: write 

jobs:

  terraform-plan:
    name: tf-plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: configure-aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume:  ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActions-Terraform-${{ github.run_id }}
      - name: setup tf 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: tf init 
        run: terraform init 
      - name: terraform fmt check 
        run: terraform fmt -check -recursive 
      - name: terraform validate
        run: terraform validate 
      - name: terraform plan
        if: ${{!inputs.tf-destroy}}
        id: plan
        run: |
          terraform plan -out=tfplan -no-color 2>&1 | tee plan_output.txt 
        continue-on-error: true
      - name: tf destroy plan
        if: inputs.tf-destroy
        run: terraform plan -destroy -out=tfplan-destroy
        continue-on-error: true
      - name: upload creation plan artifact
        if: ${{!inputs.tf-destroy}}
        uses:  actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan
      - name: upload  destroy plan artifact
        uses:  actions/upload-artifact@v4
        with:
          name: tfplan-destroy
          path: tfplan-destroy
      - name: Post plan to PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            const plan = fs.readFileSync('plan_output.txt', 'utf8');

            const maxLength = 65000;

            const truncated =
              plan.length > maxLength
                ? plan.substring(0, maxLength) + '\n...truncated'
                : plan;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform ${{ inputs.choose-environment }} Plan

              \`\`\`hcl
              ${truncated}
              \`\`\`
              `
            });
          
  terraform-apply:
    name: terraform-${{inputs.choose-environment}}
    needs: terraform-plan
    runs-on: ubuntu-latest
    if: ${{!inputs.tf-destroy || !inputs.dry-run}}
    environment: ${{inputs.choose-environment }} 
    defaults:
      run:
        working-directory: .
    steps:
      - name: echo enviroment
        run: echo ${{inputs.choose-environment}}
      - name: checkout
        uses: actions/checkout@v4
      - name: configure aws creds 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GithubActions-Terraform-${{ github.run_id }}
      - name: setup terraform 
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: check tf version
        run: terraform version 
      - name: terraform init 
        run: terraform init 
      - name: Debug
        run: |
          echo "event=${{ github.event_name }}"
          echo "ref=${{ github.ref }}"
      - name: tf plan download
        uses: actions/download-artifact@v4
        with:
          name: tfplan
      - name: terraform apply 
        if: |
          (github.ref == 'refs/heads/main' && github.event_name == 'push') || 
          (github.event_name == 'workflow_dispatch' && inputs.choose-environment == 'staging' )
        run: terraform apply tfplan

  terraform-destroy:
    name: terraform-destroy
    runs-on: ubuntu-latest 
    needs: terraform-plan
    environment: ${{inputs.choose-environment }} 
    if: | 
      github.event_name == 'workflow_dispatch' && inputs.tf-destroy || !inputs.dry-run
    defaults:
      run:
        working-directory: .
    steps:
      - name: checkout 
        uses: actions/checkout@v4
      - name: config aws creds 
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_ARN}}
          aws-region: ${{secrets.AWS_REGION}}
          role-session-name: GithubActions-Terraform-${{ github.run_id }}
      - name: setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0
      - name: tf init 
        run: terraform init 
      - name: tf plan download
        uses: actions/download-artifact@v4
        with:
          name: tfplan-destroy
      - name: tf destroy
        run: terraform apply tfplan-destroy

